name: hi

on:
  push:
    tags:
      - 'v*'
  workflow_run:
    workflows: [ "production-release" ]
    types:
      - completed

jobs:
  verify:
    if: github.event_name == 'workflow_run' && ${{ github.event.workflow_run.conclusion == 'fail' }}
    name: Github Actions 배포 상태 체크
    runs-on: ubuntu-latest

    steps:
      - name: Github Actions 배포가 실패했습니다.
        run: exit 1

  init:
    name: 성공시 트리거
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Extract Tag
        id: tag
        run: |
          git fetch --all --tags
          echo "VERSION: $(git tag --list --sort=-v:refname | head -1)"
          echo "VERSION=`echo $(git tag --list --sort=-v:refname | head -1)`" >> $GITHUB_OUTPUT

      - name: Checkout-new-tag
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ steps.tag.outputs.VERSION }}

      - name: hi
        run: |
          echo "hello world"
          echo ${{ github.event_name }}
          echo ${{ github.ref }}
          echo ${{ github.repository }}
          echo ${{ github.workspace }}
        if: github.event_name == 'workflow_run'
