name: hi

on:
  push:
    tags:
      - 'v*'
  workflow_run:
    workflows: [ "production-release" ]
    types:
      - completed
  workflow_dispatch:
    inputs:
      tag:
        description: 프로덕션 배치 롤백 시 Tag 버전 입력
        required: false
        default: null
        type: string

jobs:
  verify:
    name: Github Actions 배포 상태 체크
    runs-on: ubuntu-latest
    if: ${{ (github.event.workflow_run.conclusion == 'success' && github.event_name == 'workflow_run') || github.event_name != 'workflow_run' }}
    steps:
      - name: Github Actions 배포 성공
        run: exit 0

  tagging:
    name: 태그 배포
    needs:  verify
    runs-on: ubuntu-latest

    steps:
      - name: 태그 결정
        id: tag-type
      - if: ${{ inputs.tag }} == 'null' || !(startsWith(${{ inputs.tag }}, 'v'))
        run: echo "PRODUCTION=TRUE" >> $GITHUB_OUTPUT
      - if: ${{ inputs.tag }} != 'null' && startsWith(${{ inputs.tag }}, 'v')
        run: echo "ROLLBACK=TRUE" >> $GITHUB_OUTPUT

      - name: Extract Tag (Production)
        id: tag
      - if: ${{ steps.tag-type.outputs.PRODUCTION }} == 'TRUE'
        run: |
          echo "this is PRODUCTION"
          echo "VERSION: $(git tag --list --sort=-v:refname | head -1 | sed 's/v//g')"
          echo "VERSION=`echo $(git tag --list --sort=-v:refname | head -1 | sed 's/v//g')`" >> $GITHUB_OUTPUT
      - if: ${{ steps.tag-type.outputs.ROLLBACK }} == 'TRUE'
        run: |
          echo "this is ROLLBACK"
          echo "VERSION: ${{ inputs.tag }}"
          echo "VERSION=${{ inputs.tag }}" >> $GITHUB_OUTPUT

      - name: Checkout-new-tag
        uses: actions/checkout@v3
        with:
          ref: ${{ steps.tag.outputs.VERSION }}

      - name: hi
        run: |
          echo "hello world"
          echo ${{ steps.tag.outputs.VERSION }}
          echo ${{ github.event_name }}
          echo ${{ github.ref }}
          echo ${{ github.repository }}
          echo ${{ github.workspace }}
          echo ${{ startsWith(github.event.workflow_run.conclusion, 'success') && startsWith(github.event_name, 'workflow_run') }}
        if: startsWith(github.event.workflow_run.conclusion, 'success') && startsWith(github.event_name, 'workflow_run')
