name: hi

on:
  push:
    tags:
      - 'v*'
  workflow_run:
    workflows: [ "production-release" ]
    types:
      - completed

jobs:

  init:
    name: 성공시 트리거
    runs-on: ubuntu-latest

    steps:
      - name: hi
        run: |
          echo "hello world"
          echo ${{ github.event_name }}
          echo ${{ github.ref }}
          echo ${{ github.repository }}
          echo ${{ github.workspace }}
        if: github.ref == 'refs/heads/main'
