name: production-release

on:
  workflow_dispatch:
    inputs:
      version:
        description: release tag versioning
        required: true
        default: patch
        type: choice
        options:
        - major
        - minor
        - patch

jobs:
  release:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Set Release Type
        run: |
          echo "release tag version type: $TYPE"
        env:
          TYPE: ${{ inputs.version }}

      - name: Add release commit
        run: |
          git config --global user.name 'croquiscom-pim'
          git config --global user.email 'admin@croquis.com'
          AUTHOR="${{ github.event.sender.login }} <${{ github.event.sender.id }}+${{ github.event.sender.login }}@users.noreply.github.com>"

      - name: Calculate Next Major version Tag
        if: TYPE != 'major'
        run: |
          CUR_MAJOR_NUMBER=`git describe --tags | sed 's/v//g' | awk -F '.' '{ print $3 }'`
          echo $CUR_MAJOR_NUMBER
          NEXT_MAJOR_NUMBER=`expr $CUR_MAJOR_NUMBER + 1`
          echo $NEXT_MAJOR_NUMBER
